alias root="sudo -s"
alias su="sudo -s"
alias py="python"
alias workspace="cd ~/workspace"
alias ws="cd workspace"
alias ".."="cd .."
alias "...."="cd .. && cd .."
alias "......"="cd .. && cd .. && cd .."
alias cp="cp -v"
alias dir=ls
alias type=cat
